### PR TITLE
fix: ignore invalid urls in link rewriter

### LINKED ISSUE #328: Pipeline fails on malformed links
**Description**
Document (imported from original site) with malformed links fails the pipeline.

Page URL: https://main--moleculardevices--hlxsites.hlx.page/drafts/mhaack/cookie-notice
Docu: https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B412EADC0-C940-4195-AD74-8F4AF6EA5B25%7D&file=cookie-notice.docx&action=default&mobileredirect=true

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #328

### CODE REVIEW

File: src/steps/utils.js [hunk 1]
```diff
@@ -185,25 +185,29 @@ export function rewriteUrl(state, url) {
...
-  }
+  try {
+    const { pathname, search, hash } = new URL(url);
+
+    if (AZURE_BLOB_REGEXP.test(url)) {
+      const filename = pathname.split('/').pop();
+      const [name, props] = hash.split('?');
+      const extension = name.split('.').pop() || 'jpg';
+      const newHash = props ? `#${props}` : '';
+      return `./media_${filename}.${extension}${newHash}`;
```
Comment (dominique-pfister) [inline src/steps/utils.js:196]: so, it either returns a `path` or a URL? funny, though it was already like this before your change

**Review by dominique-pfister — APPROVED** [review]

File: src/steps/utils.js (hunk 1 above)
Comment (tripodsan) [reply src/steps/utils.js:196]: yes. the change here is only that it catches the error when `url` is not valid.
