### PR TITLE
fix: ignore urns, hrefs, code blocks for rewrite-icons

### LINKED ISSUE #348: skip rewrite-icons for certain conditions
The current behavior for icons is to rewrite any text that matches [`/:(#?[a-z_-]+[a-z\d]*):/gi`](https://github.com/adobe/helix-html-pipeline/blob/main/src/steps/rewrite-icons.js#L16) with a span

**Problem:** this replaces strings that intentionally use colons inside them, like URNs

There are a couple cases I think this could be avoided without being too much of an impact:
1. inside `code` elements
- I would argue it's unlikely authors intend to insert icons inside code blocks, at least when being used for code
- this would match github/slack functionality, eg. :+1: `:+1:`
2. inside urns/hrefs
- URNs may exist in content
- some links contain URNs or path segments that resemble URNs, eg. sharepoint
- unlikely icons are intentionally inserted into those patterns
  - `(?<!(?:https?|urn)[^\s]*):(#?[a-z_-]+[a-z\d]*):`
  - can't begin with `urn:`, `http:` or `https:`

### PR DESCRIPTION
**Pull request by maxakuru**
fix #348

### CODE REVIEW

File: src/steps/rewrite-icons.js [hunk 1]
```diff
@@ -11,9 +11,9 @@
  */
 /* eslint-disable no-param-reassign */
 import { h } from 'hastscript';
-import { CONTINUE, visit } from 'unist-util-visit';
+import { CONTINUE, SKIP, visit } from 'unist-util-visit';
 
-const REGEXP_ICON = /:(#?[a-z_-]+[a-z\d]*):/gi;
+const REGEXP_ICON = /(?<!https?[^\s]*)(?<!urn[^\s]*):(#?[a-z_-]+[a-z\d]*):/gi;
```
Comment (tripodsan) [inline src/steps/rewrite-icons.js:16]: maybe?

```suggestion
const REGEXP_ICON = /(?<!(https?|urn)[^\s]*):(#?[a-z_-]+[a-z\d]*):/gi;
```

**Review by tripodsan — APPROVED** [review]
