### PR TITLE
fix: improve custom header handling

### LINKED ISSUE #199: allow any custom header via headers.json
currently only a small set of headers are supported in the headers.json, this is a left over from where the headers were storeed in the metadata.json.

suggestion:
- allow any header to be added via the headers.json

### LINKED ISSUE #202: handle OPTIONS request for custom access-control-allow-origin smartly
the problem is that the setting the `access-control-allow-origin` via the headers.json can only be used to set the value of `*`, but doesn't allow to have qualified host names.

it would be great to allow reflecting the `origin` based on patterns.

**suggestion**
if the value for the `access-control-allow-origin` contains a regexp, use it to validate the origin and reflect it if matches.

eg:

| URL | access-control-allow-origin |
|-----|------------------------------|
| `/**`   | `/http(s)?:\/\/([a-zA-Z0-9.\-_]+[.])*adobe[.]com(\:.+)?/, /http(s)?:\/\/localhost(\:.+)?/` |

Also, it should respond with a `vary: origin` header.

### LINKED ISSUE #204: values in header.json are truncated to 1024 characters
a custom header added via the headers.json is truncated at 1024 characters.

problem is here: https://github.com/adobe/helix-html-pipeline/blob/6b84f0c0d0681ef84e62fd1ac3cf50af96e08643/src/steps/set-custom-response-headers.js#L26

`cleanupHeaderValue()` is not intended to be used for this.

### PR DESCRIPTION
**Pull request by tripodsan**
- allows values up to 64k (fixes #204)
- special handling of access-controll-allow-origin (fixes #202)
- allows any custom header (fixes #199)

### CODE REVIEW

File: src/steps/set-custom-response-headers.js [hunk 1]
```diff
@@ -9,7 +9,43 @@
  * OF ANY KIND, either express or implied. See the License for the specific language
  * governing permissions and limitations under the License.
  */
-import { cleanupHeaderValue } from '@adobe/helix-shared-utils';
+function cleanupHeaderValue(value) {
+  return value
+    .replace(/[^\t\u0020-\u007E\u0080-\u00FF]/g, '')
+    .substring(0, 1024 * 64);
```
Comment (dominique-pfister) [inline src/steps/set-custom-response-headers.js:15]: 😁

File: src/steps/set-custom-response-headers.js [hunk 2]
```diff
@@ -9,7 +9,43 @@
...
+}
+
+/**
+ * Computes the access-control-allow-origin header value.
+ * If the value can either be a single value or a comma separated list of origin names or patterns.
```
Comment (dominique-pfister) [inline src/steps/set-custom-response-headers.js:20]:
```suggestion
 * The value can either be a single value or a comma separated list of origin names or patterns.
```

**Review by dominique-pfister — APPROVED** [review]
