### PR TITLE
fix: apply folder-mapped metadata also for existing resources

### LINKED ISSUE #758: Folder mapped metadata not applied to physical pages in folder mapped paths
**Description**
When using folder mapped virtual pages, it is possible to provide a bulk metadata spreadhseet that is applied to the these virtual pages. https://www.aem.live/docs/bulk-metadata#folder-mapped-metadata

When creating a physical page inside the folder mapped path, the metadata spreadsheet is not applied anymore, only the regular and additional bulk metadata spreadsheets are applied.

Form a users point of view, metadata should be applied on a path no matter it virtual page or a physical page in a folder mapped path.

**To Reproduce**
1. setup a site with folder mapping
2. add a folder mapped metadata sheet
3. preview everything and verify the folder mapped metadata is applied to the folder mapped pages
4. create a physical page in the folder mapped path
5. the folder mapped metadata is not applied

**Expected behavior**
The folder mapped metadata is applied.

**Additional context**
https://cq-dev.slack.com/archives/C064DHSP4G2/p1732219349468749

### PR DESCRIPTION
**Pull request by tripodsan**
fixes #758

### CODE REVIEW

File: src/PipelineState.d.ts [hunk 1]
```diff
@@ -117,5 +117,22 @@ declare class PipelineState {
    */
   liveHost: string;
 
+  /**
+   * specifies if the content as folder mapped (note that it remains false for content that
```
Comment (dominique-pfister) [inline src/PipelineState.d.ts:121]: *is* folder mapped

**Review by dominique-pfister — APPROVED** [review]
