### PR TITLE
fix: treat section metadata style values like block options (#1071)

### LINKED ISSUE #1071: [section metadata] regression in style handling
**Description**
The value of the `style` propety in section metadata neds to be treated the same as [block options](https://www.aem.live/developer/markup-sections-blocks#block-options).
Currently, a value `centered dark` becomes `centered dark` in the section's class attribute, which is not backward compatible.

**Expected behavior**
Style value transformation must be like:
- `columns wide` becomes `columns-wide` (concatenation)
- `columns, wide` becomes `columns wide` (enumeration)
- `two columns (wide, dark)` becomes `two-columns wide dark` (main class with enumerated options

**Additional context**
Current client-side section metadata handling:
https://github.com/adobe/aem-lib/blob/main/src/decorate.js#L69-L82

### PR DESCRIPTION
**Pull request by rofe**
Fix #1071

### CODE REVIEW

File: src/steps/extract-section-metadata.js [hunk 1]
```diff
@@ -78,15 +78,15 @@ export default function extractSectionMetadata(state) {
...
         const name = toMetaName(toString($name));
         if (name) {
-          const value = getValueFromNode($value);
           if (name === 'style') {
             if (!parent.properties.className) {
               parent.properties.className = [];
             }
             parent.properties.className.push(
-              ...value.split(/[,\s]+/).filter(Boolean).flatMap(toBlockCSSClassNames),
+              ...toString($value).split(',').flatMap(toBlockCSSClassNames),
```
Comment (rofe) [inline src/steps/extract-section-metadata.js]: `.filter(Boolean)` is actually not needed, because `toBlockCSSClassNames` alfready handles that case.

File: test/fixtures/content/page-with-section-metadata.md [hunk 2]
```diff
@@ -39,8 +39,7 @@ Multiple styles and image metadata.
 +---------------+----------------------------------------+
 | Section Metadata                                       |
 +===============+========================================+
-| Style         | dark                                   |
-|               | centered                               |
```
Comment (tripodsan) [inline test/fixtures/content/page-with-section-metadata.md:43]: but now you removed the `newline` test case.. I think it's not handled correctly.

**Review by tripodsan — CHANGES_REQUESTED** [review]
not change test

File: test/fixtures/content/page-with-section-metadata.md (hunk 2 above)
Comment (rofe) [reply test/fixtures/content/page-with-section-metadata.md:43]: Yes, I removed this one on purpose. I don't think this is a use case seen in the wild. But we can add it back, just in case.

File: src/steps/extract-section-metadata.js [hunk 3]
```diff
@@ -78,15 +98,18 @@ export default function extractSectionMetadata(state) {
...
             if (!parent.properties.className) {
               parent.properties.className = [];
             }
+            const style = $value.children
+              .map(getStyleValueFromNode)
+              .join(',');
             parent.properties.className.push(
-              ...value.split(/[,\s]+/).filter(Boolean).flatMap(toBlockCSSClassNames),
+              ...style.split(',').flatMap(toBlockCSSClassNames),
             );
```
Comment (tripodsan) [inline src/steps/extract-section-metadata.js]: sond complicated... why not do everything in `getStyleValueFromNode()` for the entire `$value` node?

File: src/steps/extract-section-metadata.js [hunk 4]
```diff
@@ -54,6 +54,31 @@ function getValueFromNode($value) {
...
+  visit($node, (node, idx) => {
+    if (node.tagName === 'p' && idx > 0) {
+      parts.push(',');
+    }
+    if (node.tagName === 'br') {
+      parts.push(',');
+      return SKIP;
+    }
+    if (node.type === 'text') {
+      parts.push(node.value);
```
Comment (tripodsan) [inline src/steps/extract-section-metadata.js]: why not split by `,` here? so you don't need to join/split later?

Comment (rofe) [reply src/steps/extract-section-metadata.js]: Good point!

**Review by tripodsan — APPROVED** [review]
