### PR TITLE
fix: return columns as well

### LINKED ISSUE #784: [JSON] multi-sheets don't have a `columns` array
Single sheets have a `columns` array which helps clients process the data. Multi-sheets don't have it yet.

### PR DESCRIPTION
**Pull request by dominique-pfister**
fix #784

### CODE REVIEW

File: src/utils/json-filter.js [hunk 1]
```diff
@@ -36,12 +36,16 @@ export default function jsonFilter(state, res, query) {
...
-    return {
+    const ret = {
       total: dataStruct.total,
       offset,
       limit: filtered.length,
       data: filtered,
     };
+    if (dataStruct.columns) {
+      ret.columns = dataStruct.columns;
+    }
```
Comment (dominique-pfister) [inline src/utils/json-filter.js:47]: funnily, the `else` case is not reported as missing in coverage

**Review by tripodsan — APPROVED** [review]
