### PR TITLE
fix: folder mapping should only be applied if direct addressed resource is missing

### LINKED ISSUE #30: foldermapping should only be applied if direct addressed resource is missing
then a resource below a mapped folder exists, it should respect it.

eg:

```
folders:
  # generate everything on and below /products with the indicated content
  /products: /generic-product
```

if `/products/foo` exists, it should render (or redirect) `/products/foo`, 
otherwise `/generic-product`

### PR DESCRIPTION
**Pull request by ramboz**
Adjusting the html and json pipeline so they first try to fetch the content, and then only trigger the folder mapping if that request 404ed. Also adjusting the existing unit tests to address the changes, and adding a specific case to test the new use case.

## Related Issues

Fix #30

### CODE REVIEW

File: src/json-pipe.js [hunk 1]
```diff
@@ -54,6 +54,8 @@ async function fetchJsonContent(state, req, res) {
     ret = await s3Loader.getObject('helix-code-bus', `${owner}/${repo}/${ref}${path}`);
   }
   if (ret.status === 200) {
+    res.status = 200;
```
Comment (ramboz) [inline src/json-pipe.js:57]: Resetting here so we are not propagating down the errors from the first fetch

File: src/html-pipe.js [hunk 2]
```diff
@@ -82,13 +82,19 @@ export async function htmlPipe(state, req) {
     }
 
     // ...and apply the folder mapping
-    await folderMapping(state);
+    state.timer?.update('content-fetch');
+    let contentPromise = await fetchContent(state, req, res);
+    // ...but only if the current resource doesn't exist
+    if (res.status === 404) {
+      await folderMapping(state);
+      contentPromise = fetchContent(state, req, res);
```
Comment (tripodsan) [inline src/html-pipe.js:90]: this only needs to be executed if the `state.info.mapped === true`, i.e. if there was an actual remapping.
otherwise the same missing content is fetched twice.

File: src/json-pipe.js [hunk 3]
```diff
@@ -126,10 +127,18 @@ export async function jsonPipe(state, req) {
       },
     });
 
+    // apply the folder mapping if the current resource doesn't exist
     state.timer?.update('json-fetch');
+    let contentPromise = await fetchJsonContent(state, req, res);
+    if (res.status === 404) {
+      await folderMapping(state);
+      contentPromise = fetchJsonContent(state, req, res);
```
Comment (tripodsan) [inline src/json-pipe.js:135]: same here: only fetch if was mapped.

**Review by tripodsan — CHANGES_REQUESTED** [review]
avoid fetching twice for 404

File: src/html-pipe.js [hunk 4]
```diff
@@ -82,13 +82,19 @@ export async function htmlPipe(state, req) {
     }
 
     // ...and apply the folder mapping
-    await folderMapping(state);
+    state.timer?.update('content-fetch');
+    let contentPromise = await fetchContent(state, req, res);
```
Comment (trieloff) [inline src/html-pipe.js:86]:
```suggestion
    const contentPromise = await fetchContent(state, req, res);
```

Am I'm misreading this? `contentPromise` isn't being re-defined later on.

**Review by trieloff — APPROVED** [review]

File: src/html-pipe.js (hunk 4 above)
Comment (tripodsan) [reply src/html-pipe.js:86]: yes it is, on line 90

File: src/html-pipe.js [hunk 5]
```diff
@@ -82,13 +82,21 @@ export async function htmlPipe(state, req) {
...
+    // ...but only if the current resource doesn't exist
+    if (res.status === 404) {
+      await folderMapping(state);
+      if (state.info.unmappedPath) {
```
Comment (ramboz) [inline src/html-pipe.js:90]: `state.mapped` doesn't seem to be set for the code bus, nor for the json pipe, so ended up leveraging the only property that is consistently set.

**Review by tripodsan — APPROVED** [review]
