### PR TITLE
fix: Match globs for mapped pages

### LINKED ISSUE #69: metadata glob patterns not matched for folder mapped pages
Given mapping
```yaml
folders:
  /ca/en/products/category/: /ca/en/products/category/default
```

And `metadata.json`
```
URL | facets
-- | --
**/category/lighting** | bulb_shape
**/en/products/category/lighting** | bulb_shape
```
> Two attempts to target the same page.... (just for testing)

Then one would expect making a request to 
`http://localhost:3000/ca/en/products/category/lighting`

Would return this in the head.html
```html
<meta name="facets" content="bulb_shape">
```

Note: No document exists for lighting and instead the `default` document is loaded as expected.

### PR DESCRIPTION
**Pull request by dylandepass**
Fixes glob matching for mapped pages

## Related Issues
fixes #69

### CODE REVIEW

File: src/index.d.ts [hunk 1]
```diff
@@ -65,6 +65,11 @@ declare interface PathInfo {
    * original extension as passed via request
    */
   originalExtension: string;
+
+  /**
+   * original path as passed before folder mapping
+   */
+  mappedPath: string;
```
Comment (dylandepass) [inline src/index.d.ts:72]: Hate to make another prop, wasn't sure though. Should I have just overridden `originalPath`?

Comment (dylandepass) [reply src/index.d.ts:72]: True... I like `unmappedPath`.
